export default {
  cities: [
    "All Cities",
    "Ahmadpur East",
    "Ahmed Nager Chatha",
    "Alipur",
    "Ali Khan Abad",
    "Arifwala",
    "Attock",
    "Bhera",
    "Bhalwal",
    "Bahawalnagar",
    "Bahawalpur",
    "Burewala",
    "Bhakkar",
    "Chillianwala",
    "Chichawatni",
    "Chakwal",
    "Chiniot",
    "Chishtian",
    "Daska",
    "Darya Khan",
    "Dera Ghazi Khan",
    "Dhaular",
    "Dina",
    "Dinga",
    "Dipalpur",
    "Fateh Jang",
    "Faisalabad",
    "Gojra",
    "Ghakhar Mandi",
    "Gujrat",
    "Gujranwala",
    "Hafizabad",
    "Gujar Khan",
    "Haroonabad",
    "Hasilpur",
    "Haveli Lakha",
    "Islamabad",
    "Jalalpur Jattan",
    "Jampur",
    "Jaranwala",
    "Jhang",
    "Jhelum",
    "Karor Lal Esan",
    "Kasur",
    "Kalabagh",
    "Kamalia",
    "Kāmoke",
    "Khanewal",
    "Khanpur",
    "Kharian",
    "Khushab",
    "Kot Adu",
    "Jauharabad",
    "Lahore",
    "Lalamusa",
    "Layyah",
    "Liaquat Pur",
    "Lodhran",
    "Malakwal",
    "Mailsi",
    "Mamoori",
    "Mandi Bahauddin",
    "Mian Channu",
    "Mianwali",
    "Multan",
    "Murree",
    "Muridke",
    "Mianwali Bangla",
    "Muzaffargarh",
    "Narowal",
    "Okara",
    "Renala Khurd",
    "Pakpattan",
    "Pattoki",
    "Pir Mahal",
    "Qaimpur",
    "Rabwah",
    "Qila Didar Singh",
    "Raiwind",
    "Rajanpur",
    "Rahim Yar Khan",
    "Rawalpindi",
    "Sadiqabad",
    "Safdarabad",
    "Sahiwal",
    "Sangla Hill",
    "Sargodha",
    "Sarai Alamgir",
    "Sheikhupura",
    "Shakargarh",
    "Soianwala",
    "Sialkot",
    "Siranwali",
    "Sohawa",
    "Taxila",
    "Talagang",
    "Toba Tek Singh",
    "Vehari",
    "Wah Cantonment",
    "Wazirabad",
    "Badin",
    "Bhirkan",
    "Bhiria City",
    "Bandhi",
    "Bhiria Road",
    "Rajo Khanani",
    "Dadu",
    "Chak",
    "Daulatpur",
    "Digri",
    "Diplo",
    "Dokri",
    "Gambat",
    "Garhi Yasin",
    "Ghotki",
    "Daharki",
    "Mirpur Mathelo",
    "Hyderabad",
    "Khairpur Mirs'",
    "Islamkot",
    "Jamshoro",
    "Ubaro",
    "Jacobabad",
    "Jungshahi",
    "Kandhkot",
    "Kandiaro",
    "Karachi",
    "Kashmore",
    "Keti Bandar",
    "Khairpur",
    "Khadro",
    "Khipro",
    "Korangi",
    "Kotri",
    "Larkana",
    "Malir",
    "Mehar",
    "Matiari",
    "Mirpur Khas",
    "Madeji",
    "Miranpur",
    "Mithani",
    "Mithi",
    "Mehrabpur",
    "Moro",
    "Nagarparkar",
    "Naudero",
    "Naushahro Feroze",
    "Qambar",
    "Nawabshah",
    "Sijawal Junejo",
    "Qasimabad",
    "Ratodero",
    "Ranipur",
    "Sakrand",
    "Rohri",
    "Sehwan Sharif",
    "Sanghar",
    "Shahdadkot",
    "Shahbandar",
    "Shikarpaur",
    "Shahdadpur",
    "Sinjhoro",
    "Shahpur Chakar",
    "Sukkur",
    "Sobho Dero",
    "Tando Adam Khan",
    "Tangwani",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Thari Mirwah",
    "Umerkot",
    "Warah",
    "Thatta",
    "Piryaloi",
    "Tharushah",
    "Sita Road",
    "Pir Jo Goth",
    "Shahpur jahania",
    "Qubo Saeed Khan",
    "Samaro",
    "Mehrabpur",
    "Maqsoodo Rind",
    "Sann",
    "Lakhi ghulam shah",
    "Manjhand",
    "Mian Sahib",
    "Nasirabad",
    "Kunri",
    "Boriri",
    "Thul",
    "Bela",
    "Chaman",
    "Dadhar",
    "Gwadar",
    "Dera Bugti",
    "Jiwani",
    "Hala",
    "Kalat",
    "Kharan",
    "Kot Malik",
    "Loralai",
    "Mehrabpur",
    "Mach",
    "Mastung",
    "Nushki",
    "Pishin",
    "Pasni",
    "Quetta",
    "Turbat",
    "Sibi",
    "Usta Muhammad",
    "Uthal",
    "Zhob",
    "Alpuri",
    "Abbottabad",
    "Adezai",
    "Akora Khattak",
    "Ayubia",
    "Batkhela",
    "Bannu",
    "Banda Daud Shah",
    "Battagram",
    "Birote",
    "Charsadda",
    "Chakdara",
    "Chitral",
    "Daggar",
    "Dera Ismail Khan",
    "Darya Khan",
    "Dargai",
    "Doaba",
    "Dir",
    "Drosh",
    "Hangu",
    "Haripur",
    "Karak",
    "Kulachi",
    "Kohat",
    "Lakki Marwat",
    "Latamber",
    "Madyan",
    "Mardan",
    "Mansehra",
    "Mastuj",
    "Mingora",
    "Nowshera",
    "Pabbi",
    "Paharpur",
    "Peshawar",
    "Shorkot",
    "Saidu Sharif",
    "Shewa Adda",
    "Swabi",
    "Tank",
    "Swat",
    "Tangi",
    "Thall",
    "Timergara",
    "Tordher",
    "Bagh",
    "Bhimbar",
    "Hattian Bala",
    "Haveli",
    "Kotli",
    "Muzaffarabad",
    "Neelam Valley",
    "Mirpur",
    "Rawalakot",
    "Sudhanoti"
  ]
};
