export const SET_CAT_SUCCESS = "SETCATSUCCESS";
export const SET_CAT_FAIL = "SETCATFAIL";

export const SET_SUBCAT_SUCCESS = "SETSUBCATSUCCESS";
export const SET_SUBCAT_FAIL = "SETSUBCATFAIL";

export const SET_SUBSUBCAT_SUCCESS = "SETSUBSUBCATSUCCESS";
export const SET_SUBSUBCAT_FAIL = "SETSUBSUBCATFAIL";

export const SET_NAME_SUCCESS = "SETNAMESUCCESS";
export const SET_NAME_FAIL = "SETNAMEFAIL";

export const SET_PRICE_SUCCESS = "SETPRICESUCCESS";
export const SET_PRICE_FAIL = "SETPRICEFAIL";

export const SET_CITY_SUCCESS = "SETCITYSUCCESS";
export const SET_CITY_FAIL = "SETCITYFAIL";

export const REFRESH_STATE = "REFRESHSTATE";
