export const SET_NAME_SUCCESS = "SETNAMESUCCESS";
export const SET_NAME_FAIL = "SETNAMEFAIL";

export const SET_PRICE_SUCCESS = "SETPRICESUCCESS";
export const SET_PRICE_FAIL = "SETPRICEFAIL";

export const SET_CAT_SUCCESS = "SETCATSUCCESS";
export const SET_CAT_FAIL = "SETCATFAIL";

export const SET_SUBCAT_SUCCESS = "SETSUBCATSUCCESS";
export const SET_SUBCAT_FAIL = "SETSUBCATFAIL";

export const SET_SUBSUBCAT_SUCCESS = "SETSUBSUBCATSUCCESS";
export const SET_SUBSUBCAT_FAIL = "SETSUBSUBCATFAIL";

export const SET_DESC_SUCCESS = "SETDESCSUCCESS";
export const SET_DESC_FAIL = "SETDESCFAIL";

export const SET_ATT_SUCCESS = "SETATTSUCCESS";
export const SET_ATT_FAIL = "SETATTFAIL";

export const SET_INSTALLMENTPLAN_SUCCESS = "SETINSTALLMENTPLANSUCCESS";
export const SET_INSTALLMENTPLAN_FAIL = "SETINSTALLMENTPLANFAIL";

export const SET_REMAINING_SUCCESS = "SETREMAININGSUCCESS";
export const SET_REMAINING_FAIL = "SETREMAININGFAIL";

export const SET_DOWNPAYMENT_SUCCESS = "SETDOWNPAYMENTSUCCESS";
export const SET_DOWNPAYMENT_FAIL = "SETDOWNPAYMENTFAIL";

export const SET_DURATION_SUCCESS = "SETDURATIONSUCCESS";
export const SET_DURATION_FAIL = "SETDURATIONFAIL";

export const SET_IMAGES_SUCCESS = "SETIMAGESSUCCESS";
export const SET_IMAGES_FAIL = "SETIMAGESFAIL";

export const REFRESH_STATE = "REFRESHSTATE";
export const SET_ALL_DATA = "SETALLDATA";
