export const SET_NAME = "SETNAME";
export const SET_EMAIL = "SETEMAIL";
export const SET_CITY = "SETCITY";
export const SET_TITLE = "SETTITLE";
export const SET_CONTACT = "SETCONTACT";
export const SET_ADDRESS = "SETADDRESS";
export const SET_PASSWORD = "SETPASSWORD";
export const SET_CONFIRM_PASSWORD = "SETCONFIRMPASSWORD";

export const SET_NAMEERROR = "SETNAMEERROR";
export const SET_EMAILERROR = "SETEMAILERROR";
export const SET_CITYERROR = "SETCITYERROR";
export const SET_TITLEERROR = "SETTITLEERROR";
export const SET_CONTACTERROR = "SETCONTACTERROR";
export const SET_ADDRESSERROR = "SETADDRESSERROR";
export const SET_PASSWORDERROR = "SETPASSWORDERROR";
export const SET_CONFIRM_PASSWORDERROR = "SETCONFIRMPASSWORDERROR";
