export const ALL_CATS_LOADED_SUCCESS = "ALLCATSLOADEDSUCCESS";
export const ALL_CATS_LOADED_FAILED = "ALLCATSLOADEDFAILED";
export const START_BUFFERRING = "STARTBUFFERRING";
export const END_BUFFERRING_WITH_ERROR = "ENDBUFFERRINGWITHERROR";
export const END_BUFFERRING_WITH_SUCCESS = "ENDBUFFERRINGWITHSUCCESS";
export const REFRESH = "REFRESHPRODUCTEDIT";
