export const SHOWSIGNIN = "SHOWSIGNIN";
export const SHOWREGISTER = "SHOWREGISTER";
export const HIDESIGNIN = "HIDESIGNIN";
export const HIDEREGISTER = "HIDEREGISTER";

export const REGISTERED_SUCCESS = "REGISTEREDSUCCESS";
export const REGISTERED_FAILED = "REGISTERED_FAILED";
export const START_BUFFERRING = "STARTBUFFERRING";
export const END_BUFFERRING = "ENDBUFFERRING";

export const SIGNIN_FAILED = "SIGNINFAILED";
export const START_SIGNIN_BUFFERRING = "STARTSIGNINBUFFERRING";
export const END_SIGNIN_BUFFERRING = "ENDSIGNINBUFFERRING";
