export const SHOWSIGNIN = "BUYERSHOWSIGNIN";
export const SHOWREGISTER = "BUYERSHOWREGISTER";
export const HIDESIGNIN = "BUYERHIDESIGNIN";
export const HIDEREGISTER = "BUYERHIDEREGISTER";

export const REGISTERED_SUCCESS = "BUYERREGISTEREDSUCCESS";
export const REGISTERED_FAILED = "BUYERREGISTERED_FAILED";
export const START_BUFFERRING = "BUYERSTARTBUFFERRING";
export const END_BUFFERRING = "BUYERENDBUFFERRING";

export const SIGNIN_FAILED = "BUYERSIGNINFAILED";
export const START_SIGNIN_BUFFERRING = "BUYERSTARTSIGNINBUFFERRING";
export const END_SIGNIN_BUFFERRING = "BUYERENDSIGNINBUFFERRING";
